---
- hosts: all
  tasks:
    - name: install packages
      yum: name={{ item }} state=latest
      with_items:
      - vim
      - nano
      - wget
      - tcpdump
      - strace
      - bind-utils
      - pam_ldap
      - nscd
      - nss-pam-ldapd
      - openldap-clients
      - git
      - ntp
      - zip
      - unzip

    - name: enable ntpd
      systemd:
        name: ntpd
        enabled: yes
        state: started
